### ISSUE TITLE
libboost cannot be open

### ISSUE THREAD

**Issue by drgndomdev** [drgndomdev/quickdashboard#3]
When trying to run the program I get the following error: 
`./main: error while loading shared libraries: libboost_system.so.1.79.0: cannot open shared object file: No such file or directory`

I look in-depth and it seems like libboost is located in a different directory compared to the other libraries. I was considering specifying new LD_LIBRARY_PATH. However, I found there is another way to add them to the dynamic linker which is located in /etc/ld.so.conf

The only problem with this is the libboost_system.so file is located in usr/local/lib, and there are thousands of other libraries.

@Twon

**Comment by Twon** [comment]
Yes, ok, I know how to fix this.  Let me raise a PR which shows you how to do this and then I can explain the steps.

You can, of course, modify /etc/ld.so.conf but this is local to your system so will not work for anyone else building the project.  We'll fix this by using RPaths in the build executable.  This is a quick summary of modifying rpaths in CMake: https://dev.my-gate.net/2021/08/04/understanding-rpath-with-cmake/

**Comment by Twon** [comment]
Try this branch out, this should fix the issue locally (though note the embedded RPaths will not necessarily work on another machine depending on if or where boost is installed): https://github.com/drgndomdev/quickdashboard/pull/4

Solving that aspect is trickier and is where package managers come into their own
